### ISSUE TITLE
Issues with GAM in R 

### ISSUE THREAD

**Issue by CardosoJr** [vios-s/DiffAN#1]
First of all, thank you for the amazing paper and code. It's a very interesting method. 

I have been facing issues with GAM method in train_gam.R file where you call `mod_gam <- gam(formula=formula(labs), data=dat)`. 

The error message is 

> "Error in smooth.construct.tp.smooth.spec(object, data, knots): A term has fewer unique covariate combinations than specified maximum degrees of freedom"

I have tried lowering the _**k**_ argument in each variable (also checking the number of unique levels in each one in order to be more certain), but still no success. 

Have you faced the same problem?

**Comment by SANCHES-Pedro** [comment]
Hi Anilton,

thanks for the interest. Sorry, but I have not encoutered this error before.

All the R code has been directly copied from [CAM package](https://rdrr.io/cran/CAM/man/CAM-package.html).

I advise you to ask them about it.

Best,
Pedro
