### ISSUE TITLE
Fail to install requirements on Docker image

### ISSUE THREAD

**Issue by felixleopoldo** [vios-s/DiffAN#2]
Hi,

Thanks for providing DiffAN. I'm trying to install your requirements on a Docker image. However, pip seems to fail to install pydot. Do you maybe have an official Docker image that one can use or a better Dockerfile? 

This is the content of the Dockerfile I'm trying to build:

FROM continuumio/anaconda3:2022.10
RUN git clone https://github.com/vios-s/DiffAN.git
WORKDIR /DiffAN

RUN conda env create -f environment.yml

**Comment by SANCHES-Pedro** [comment]
Hi Felix,

I havent been using a Docker image for this project. I've only create a conda environment. Sorry.
